In [71]:
import numpy as np
# numpy allows us to works with arrays

In [72]:
abc = np.array([[1,2,3],[4,5,6]]) #the 2 smaller brackets are in 2 rows
abc

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
print(abc.ndim) #print the number of dimension abc is
print(abc.shape) #rows , columns
print(abc.size) # rows x columns
print(abc.dtype)

2
(2, 3)
6
int64


In [74]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [75]:
np.ones_like(abc) #but twos not usable!

array([[1, 1, 1],
       [1, 1, 1]])

In [76]:
np.zeros([2,3,3]) #now it is list but not tuples

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [77]:
np.arange(1,10,2) #1D array from 1 up to but not including 10 in steps of 2

array([1, 3, 5, 7, 9])

In [78]:
np.zeros([4,2,3]) # 4 blocks/layers, 2 rows, 3 columns - 4 matrices, each of shape (2, 3), still 3-D array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [79]:
# 3x4 array of random integers that range between 1 up but not including 10
np.random.randint(1,10,(3,4))

array([[6, 6, 4, 5],
       [6, 6, 1, 7],
       [7, 4, 3, 5]], dtype=int32)

In [80]:
# creates reproducible random number, but fixed after generating - seed!
np.random.seed(12) 
# this 12 has no attribute to the maximum value that can be randomly generated
# this 12 can be changed to anything even string, it just acts like a variable
np.random.randint(1,20, (4,5,2))

array([[[12,  7],
        [18,  3],
        [ 4,  4],
        [13, 17],
        [18,  6]],

       [[14,  3],
        [12, 11],
        [ 1,  9],
        [13, 14],
        [19,  4]],

       [[ 5,  4],
        [ 2,  1],
        [19, 19],
        [17,  7],
        [14, 10]],

       [[14, 17],
        [ 1, 15],
        [16,  2],
        [ 5,  1],
        [ 5,  2]]], dtype=int32)

In [ ]:
bbb = np.array([[5,4,3,2,1,0], [10,8,6,4,2,0]]) #total 12 items
bbb

array([[ 5,  4,  3,  2,  1,  0],
       [10,  8,  6,  4,  2,  0]])

In [ ]:
bbb.T # T stands for transpose

array([[ 5, 10],
       [ 4,  8],
       [ 3,  6],
       [ 2,  4],
       [ 1,  2],
       [ 0,  0]])

In [83]:
bbb.reshape(4,3)

array([[ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0]])

In [84]:
bbb.reshape(12,1)

array([[ 5],
       [ 4],
       [ 3],
       [ 2],
       [ 1],
       [ 0],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2],
       [ 0]])

In [85]:
bbb.reshape(1,12)

array([[ 5,  4,  3,  2,  1,  0, 10,  8,  6,  4,  2,  0]])

In [87]:
bbb

array([[ 5,  4,  3,  2,  1,  0],
       [10,  8,  6,  4,  2,  0]])

In [ ]:
np.hstack((abc,bbb)) #stack horizontally

array([[ 1,  2,  3,  5,  4,  3,  2,  1,  0],
       [ 4,  5,  6, 10,  8,  6,  4,  2,  0]])

In [ ]:
np.vstack((abc,bbb)) #stack vertically - but what is the function??

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 6

In [ ]:
r_bbb = np.reshape(bbb, (4,3)) 

In [95]:
np.vstack((abc, r_bbb))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0]])