In [7]:
# for loop

vowels = ['a', 'e', 'i', 'o', '']

for i in vowels:
  print(f'Give me an {i}!')

Give me an a!
Give me an e!
Give me an i!
Give me an o!
Give me an !


In [5]:
for i in range(10):
  print(i, i*2)

0 0
1 2
2 4
3 6
4 8
5 10
6 12
7 14
8 16
9 18


In [10]:
input_files = ['data_01.csv', 'data_02.csv', 'data_03.csv', 'data_04.csv']
output_files = []

for i in input_files:
  output_files_name = 'processed_' + i.replace('.csv', '.xlsx')
  output_files.append(output_files_name)
  print(output_files)

['processed_data_01.xlsx']
['processed_data_01.xlsx', 'processed_data_02.xlsx']
['processed_data_01.xlsx', 'processed_data_02.xlsx', 'processed_data_03.xlsx']
['processed_data_01.xlsx', 'processed_data_02.xlsx', 'processed_data_03.xlsx', 'processed_data_04.xlsx']


In [13]:
stops = ['Sheppard-Yonge', 'Bayview', 'Bessarion', 'Leslie', 'Don Mills']

for idx, stop in enumerate(stops):
  if idx == 1:
    print(f'Stop {idx + 1} is {stop}')

Stop 2 is Bayview


In [19]:
lats = (43.640, 45.520, 49.280)
lons = (-79.380, -73.570, -123.130, 0, -12.200)

for i, j in zip(lats, lons):
  print(f'({tuple(i,j)})')

TypeError: ignored

In [ ]:
olympics_cities = {2020: 'Tokyo', 2016: 'Rio de Janiero', 2012: 'London'}
olympics_cities

In [21]:
all_olympics_hosts = {'summer': olympics_cities,
                     'winter': {2022: 'Beijing', 2018: 'Pyeongchang'}}
all_olympics_hosts

{'summer': {2020: 'Tokyo', 2016: 'Rio de Janiero', 2012: 'London'},
 'winter': {2022: 'Beijing', 2018: 'Pyeongchang'}}

In [22]:
all_olympics_hosts.items()

dict_items([('summer', {2020: 'Tokyo', 2016: 'Rio de Janiero', 2012: 'London'}), ('winter', {2022: 'Beijing', 2018: 'Pyeongchang'})])

In [23]:
for key, value in all_olympics_hosts.items():
  # key --> 'winter'
  # value --> {2022: 'Beijing', 2018: 'Pyeongchang'}
  for year, city in value.items():
    # year --> '2018'
    # city --> 'Pyeongchang'
    print(f'The {year} {key.title()} Olympics were in {city}.')

The 2020 Summer Olympics were in Tokyo.
The 2016 Summer Olympics were in Rio de Janiero.
The 2012 Summer Olympics were in London.
The 2022 Winter Olympics were in Beijing.
The 2018 Winter Olympics were in Pyeongchang.


In [24]:
for i in range(5):
  # 2
  for j in ['dog', 'cat', 'bird']:
    # 'bird'
    print(i, j)


0 dog
0 cat
0 bird
1 dog
1 cat
1 bird
2 dog
2 cat
2 bird
3 dog
3 cat
3 bird
4 dog
4 cat
4 bird


In [25]:
# while loops

countdown = 4

while countdown > 0:
  print(countdown)
  countdown -= 1

4
3
2
1


In [29]:
# run this on your own time to try it out
# to interrupt this infinite loop: ctrl+m+i OR Runtime --> Interrupt execution
countdown = 4

while countdown > 0:
  print(countdown)
  break

4


In [27]:
countdown = 4

while countdown > 0:
  print(countdown)
  if countdown == 3:
    print('We are breaking the loop early.')
    break
  countdown -= 1

print('Done iterating')

4
3
We are breaking the loop early.
Done iterating


In [31]:
wishes = 3
while wishes > 0:
  wish = input('Make a wish: ')
  if 'infinite wishes' in wish.lower():
    print('You can\'t do that!')
    continue
  else:
    print('Wish granted.')
  wishes -= 1

print('You have used all your wishes.')


Make a wish: infinite wishes
You can't do that!
Make a wish: INFINITE WISHES
You can't do that!


KeyboardInterrupt: ignored

In [32]:
import math

In [33]:
math.pi

3.141592653589793

In [35]:
math.gcd(232, 18356)

4

In [36]:
pi

NameError: ignored

In [37]:
gcd

NameError: ignored

In [38]:
from math import pi

In [40]:
from datetime import date

In [41]:
print(date.today())

2023-12-16


In [42]:
from datetime import datetime

In [43]:
print(datetime.today())

2023-12-16 15:16:58.893799


In [44]:
from datetime import datetime
import pytz

# Get the current date and time in Toronto timezone
toronto_timezone = pytz.timezone('America/Toronto')
current_time = datetime.now(toronto_timezone)
print(current_time)

2023-12-16 10:17:29.405585-05:00


In [45]:
import re

In [60]:
text = '''My favorite thing to do on nice days is program.
Programming is fun as long as there aren't too many bugs!'''

| Character | Meaning |
|---|---|
| * | Match zero or more of the RE before |
| + | Match one or more of the RE before |
| ? | Match zero or one of the RE before |
| \ | Escape character |
| \d | Match any decimal digit |
| \s | Match any whitespace |
| \w | Match any word character (letters, digits, underscore) |
| [aeiou] | Match any of the characters in brackets |

In [56]:
if re.search('favou?rite', text):
  print('Text includes favourites')
else:
  print('Text is about something else')

Text is about something else


In [61]:
# match any word character (letters, digits, underscore)
# match ZERO or MORE of the RE before

re.findall('\w*ing', text)

['thing', 'Programming']

| `open()` mode | Description |
|---|---|
|`'r'` | Read-only. Produces an error if the file does not already exist. |
|`'w'` | Write. Creates a new file if one does not exist. If the file already exists, the current contents are deleted and overwritten. |
|`'a'`| Append. Adds to an existing file. If the file does not exist, it will be created. |

Paths can be absolute, like C:/Users/Owner/Documents/data/demo_data.csv, or relative, like data/demo_data.csv. Relative paths are relative to the folder the Python file is in -- if our code is not in Documents, data/demo_data.csv won't work.



In [62]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


* `read()` returns the full file contents, which can be overwhelming for larger files.
* `readline()` returns only the next line in the file. Python keeps track of where it is in the file.
* `readlines()` returns the full file as a list. Each item is one line in the file.

```
`# This is formatted as code`
```



In [68]:
with open('/content/drive/MyDrive/Colab Notebooks/data/california_housing_test.csv', 'r') as f:
    for i in range(5):
      print(f.readline())

"longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income","median_house_value"

-122.050000,37.370000,27.000000,3885.000000,661.000000,1537.000000,606.000000,6.608500,344700.000000

-118.300000,34.260000,43.000000,1510.000000,310.000000,809.000000,277.000000,3.599000,176500.000000

-117.810000,33.780000,27.000000,3589.000000,507.000000,1484.000000,495.000000,5.793400,270500.000000

-118.360000,33.820000,28.000000,67.000000,15.000000,49.000000,11.000000,6.135900,330000.000000



* `write()` writes a string to file.
* `writelines()` writes each item in an iterable to file, with no separating text in between.

In [69]:
provinces = ['BC', 'AB', 'SK', 'MB']
with open('provinces.txt', 'w') as province_file:
  province_file.writelines(provinces)

In [70]:
with open('provinces.txt', 'r') as province_file:
  print(province_file.read())

BCABSKMB


In [71]:
import os

In [72]:
os.getcwd()

'/content'

In [73]:
os.listdir()

['.config', 'drive', 'provinces.txt', 'sample_data']

In [75]:
os.listdir('sample_data')

['README.md',
 'anscombe.json',
 'california_housing_test.csv',
 'mnist_train_small.csv',
 'mnist_test.csv',
 'california_housing_train.csv']

In [74]:
for i in os.listdir('sample_data'):
  print(i)

README.md
anscombe.json
california_housing_test.csv
mnist_train_small.csv
mnist_test.csv
california_housing_train.csv


In [78]:
os.getcwd()

'/content'

In [79]:
os.listdir('sample_data')

['README.md',
 'anscombe.json',
 'california_housing_test.csv',
 'mnist_train_small.csv',
 'mnist_test.csv',
 'california_housing_train.csv']

In [76]:
cwd = os.getcwd()
full_paths = []
for i in os.listdir('sample_data'):
  full_paths.append(os.path.join(cwd, 'sample_data', i))

full_paths

['/content/sample_data/README.md',
 '/content/sample_data/anscombe.json',
 '/content/sample_data/california_housing_test.csv',
 '/content/sample_data/mnist_train_small.csv',
 '/content/sample_data/mnist_test.csv',
 '/content/sample_data/california_housing_train.csv']

In [83]:
text = 'Lavender is a small purple flower'
if os.path.exists('plants.txt'):
  print('plants.txt already exists')
else:
  with open('plants.txt', 'w') as f:
    f.write(text)


plants.txt already exists


In [85]:
with open('plants.txt', 'r') as f:
  print(f.read())

Lavender is a small purple flower


In [ ]:
# objects --> attributes & methods


# classes --> how we model an object, template that defines an
# object's attributes and methods

# class BasketballPlayer
# attributes: position, team, jersey_number
# methods: dribble(),shoot(), pass_ball(player)

In [86]:
class Dataset:
  '''Data values and methods to summarize them'''

  def __init__(self, values):
    '''Create a new dataset with values as list'''
    self.values = values
    self.size = len(values)

  def unique(self):
    '''Return a list of unique values'''
    return list(set(self.values))

  def mean(self):
    '''Return the mean of all numeric values'''
    numbers = []

    for i in self.values:
      if type(i) is int or type(i) is float:
        numbers.append(i)

    return sum(numbers)/len(numbers)


In [87]:
grades = Dataset([90, 87, 70, 70, 87, 'A'])

In [88]:
print(grades.size)

6


In [89]:
print(grades.values)

[90, 87, 70, 70, 87, 'A']


In [90]:
print(grades.mean())

80.8


In [91]:
print(grades.unique())

[90, 'A', 70, 87]


In [ ]:
# numpy


| `numpy` arrays | Python `list` |
|---|---|
| all elements must be the same type | elements can be different types |
| fixed size | can change size |
| n-dimensional | 1-dimensional |
| faster to process | slower to process |
| consumes less memory | consumes more memory |

In [92]:
import numpy as np

In [93]:
a = np.array([[1, 2, 3],[3, 2, 1]])
# first axis has a length of 2
# second axis has a length of 3

In [94]:
a

array([[1, 2, 3],
       [3, 2, 1]])

In [95]:
print(a.ndim)

2


In [96]:
print(a.shape)

(2, 3)


In [97]:
print(a.size)

6


In [98]:
print(a.dtype)

int64


In [99]:
# 2x3x2 array of zeros
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [100]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])