### 1. What is an Array?

1. **Definition**: Arrays are a collection of elements that are all of the same type. In Python, arrays are not a built-in data type but are available through libraries like `array` (for basic functionality) or `NumPy` (for more advanced operations, especially in scientific computing).
2. **Fixed Type**: Unlike lists, all elements in an array must be of the same data type (e.g., all integers, all floats).
3. **Performance**: Arrays are generally more efficient for numerical operations. They use less memory and offer better performance, especially for large amounts of data.
4. **Syntax**: In Python, a basic array from the `array` module is defined as: `import array; my_array = array.array('i', [1, 2, 3, 4])`, where `'i'` is the type code for integers.
5. **Use Cases**: Arrays are used when you need to perform mathematical operations on large datasets, especially in fields like data analysis, machine learning, and scientific computing.

### 2. Dimensions in Arrays

Each level of square brackets can be thought of as moving one dimension deeper into the array.
- **One-Dimensional (1D) Array**: This is like a single row of elements. You can think of it as a straight line where each element has its position or index. 

In [5]:
import numpy as np
oneDimArr = np.array([1, 2, 3])

- **Two-Dimensional (2D) Array**: This is like a table or a matrix. It has rows and columns. Think of it as a chessboard where you have both rows (horizontal) and columns (vertical). Each element is identified by two indexes: one for the row and one for the column.

In [3]:
twoDimArr = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

- **Three-Dimensional (3D) Array**: Imagine a cube made of smaller cubes. A 3D array has depth in addition to rows and columns. Each element is identified by three indexes: row, column, and depth. It's like a "stack" of 2D arrays. For example:

In [4]:
threeDimArr = np.array([[[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]],
                      [[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]],
                      [[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]]])

 ### 3. Why Use Multi-Dimensional Arrays?

Multi-dimensional arrays are useful for various types of data representation:
- **2D Arrays**: Often used for matrices in mathematics, spreadsheets, or for representing grids in games.
- **3D Arrays**: Useful in 3D graphics, scientific data (like MRI scans), and more complex data structures.

In [6]:
a = np.array([[1, 2, 3],
              [3, 2, 1]])

a

array([[1, 2, 3],
       [3, 2, 1]])

In [7]:
print(a.ndim)

2


In [8]:
print(a.shape)

(2, 3)


In [9]:
print(a.size)

6


In [10]:
print(a.dtype)

int64


In [11]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
a

array([[1, 2, 3],
       [3, 2, 1]])

In [13]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [15]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [41]:
np.random.seed(10000000)
np.random.randint(1, 10, (3, 4))

array([[4, 9, 5, 5],
       [8, 2, 9, 8],
       [4, 4, 1, 4]])

In [44]:
np.random.seed(1)
np.random.randint(1, 10, (3, 4))

array([[6, 9, 6, 1],
       [1, 2, 8, 7],
       [3, 5, 6, 3]])

In [45]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [46]:
onedim_arr = np.array([1, 2, 3, 4, 5])
multidim_arr = np.repeat(onedim_arr, 5)
multidim_arr

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5])

In [47]:
multidim_arr = np.tile(onedim_arr, (5, 1))
multidim_arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [50]:
another_arr = np.tile(onedim_arr, (2, 3))
another_arr

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])

In [58]:
# create a sample generator
rng = np.random.default_rng(seed=2)

# create a 5 x 4 array with normally distributed data
# mean of 10, standard deviation of 2.5
randrng = rng.normal(10, 2.5, (5, 4))
randrng

array([[10.47263345,  8.6931289 ,  8.96734114,  3.89633154],
       [14.49926846, 12.86041468,  9.18644291, 11.93451647],
       [10.70302667,  8.61544291, 12.44391863,  9.22360863],
       [ 9.17794024,  8.01963311, 11.13739518,  9.75200487],
       [11.36322178,  8.48203575, 10.31706962,  7.76931489]])

In [60]:
# Poisson distribution

# lam is 1, size 5 x 6

poissonrng = rng.poisson(1, (5, 6))
poissonrng

array([[0, 2, 0, 2, 0, 0],
       [0, 3, 1, 2, 3, 1],
       [1, 0, 0, 1, 2, 3],
       [0, 0, 0, 1, 0, 1],
       [1, 1, 3, 2, 2, 0]])

In [62]:
b = np.array([[5, 4, 3, 2, 1, 0],
             [10, 8, 6, 4, 2, 0]])
b

array([[ 5,  4,  3,  2,  1,  0],
       [10,  8,  6,  4,  2,  0]])

In [63]:
b.T

array([[ 5, 10],
       [ 4,  8],
       [ 3,  6],
       [ 2,  4],
       [ 1,  2],
       [ 0,  0]])

In [66]:
b.reshape(4, 3)

array([[ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0]])

In [67]:
b.flatten()

array([ 5,  4,  3,  2,  1,  0, 10,  8,  6,  4,  2,  0])

In [68]:
a # 2 x 3

array([[1, 2, 3],
       [3, 2, 1]])

In [69]:
b # 2 x 6

array([[ 5,  4,  3,  2,  1,  0],
       [10,  8,  6,  4,  2,  0]])

In [70]:
np.hstack((b, a))

array([[ 5,  4,  3,  2,  1,  0,  1,  2,  3],
       [10,  8,  6,  4,  2,  0,  3,  2,  1]])

In [77]:
b = b.reshape(4, 3) # 4 x 3

In [78]:
b

array([[ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0]])

In [72]:
a # 2 x 3

array([[1, 2, 3],
       [3, 2, 1]])

In [73]:
np.vstack((b.reshape(4, 3), a))

array([[ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0],
       [ 1,  2,  3],
       [ 3,  2,  1]])

In [74]:
arr1 = np.array([5, 10, 15, 20])
arr1

array([ 5, 10, 15, 20])

In [84]:
arr2 = np.arange(5, 9)
arr2

array([5, 6, 7, 8])

In [79]:
arr1 - arr2

array([ 0,  4,  8, 12])

In [80]:
arr1 * 2

array([10, 20, 30, 40])

In [82]:
arr1 + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [85]:
arr1.sum()

50

In [86]:
arr1

array([ 5, 10, 15, 20])

In [87]:
arr1.max()

20

In [88]:
arr1.mean()

12.5

In [89]:
tens = np.arange(0, 120, 10).reshape(3, 4)

tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [91]:
horizontal = np.array([-5, -10, -15, -20])
horizontal

array([ -5, -10, -15, -20])

In [92]:
tens + horizontal

array([[-5,  0,  5, 10],
       [35, 40, 45, 50],
       [75, 80, 85, 90]])

In [93]:
vertical = np.array([[100],
                     [200],
                     [300]])

In [94]:
tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [95]:
vertical

array([[100],
       [200],
       [300]])

In [96]:
tens + vertical

array([[100, 110, 120, 130],
       [240, 250, 260, 270],
       [380, 390, 400, 410]])

In [97]:
# axis = 0: Column-wise operation (down the rows)
# axis = 1: Row-wise operation (across the columns)

tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [98]:
tens.mean(axis=0)

array([40., 50., 60., 70.])

In [102]:
tens.mean(axis=1).dtype

dtype('float64')

In [100]:
(40 + 50 + 60 + 70)/4

55.0

In [101]:
arr1

array([ 5, 10, 15, 20])

In [103]:
arr1[1]

10

In [104]:
arr1[1:3]

array([10, 15])

In [105]:
tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [106]:
tens[1, 2]

60

In [107]:
tens[0]

array([ 0, 10, 20, 30])

In [108]:
tens[:, 0]

array([ 0, 40, 80])

In [109]:
tens[0:2, 1:3]

array([[10, 20],
       [50, 60]])

In [111]:
matrix = np.random.randint(1, 11, 12).reshape(3, 4)

In [112]:
matrix

array([[ 5,  3,  5,  8],
       [ 8, 10,  2,  8],
       [ 1,  7, 10, 10]])

In [113]:
matrix2 = matrix

In [114]:
matrix2[1] = [0, 0, 0, 0]

In [115]:
matrix2

array([[ 5,  3,  5,  8],
       [ 0,  0,  0,  0],
       [ 1,  7, 10, 10]])

In [116]:
matrix

array([[ 5,  3,  5,  8],
       [ 0,  0,  0,  0],
       [ 1,  7, 10, 10]])

In [117]:
matrix3 = matrix.copy()

In [118]:
matrix[1] = [1, 1, 1, 1]

In [119]:
matrix3

array([[ 5,  3,  5,  8],
       [ 0,  0,  0,  0],
       [ 1,  7, 10, 10]])

In [120]:
tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [121]:
tens % 3 == 0 # evaluate whether each element is divisible by 3

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False]])

In [122]:
tens[tens % 3 == 0]

array([ 0, 30, 60, 90])

In [123]:
mask = tens % 3 == 0
tens[mask]

array([ 0, 30, 60, 90])

In [124]:
mask2 = tens == 50

In [125]:
mask2

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [126]:
tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [127]:
tens[mask2]

array([50])

In [129]:
np.where(tens == 50, # condition
         'YAY', # return 'YAY' if True
         0) # return 'NAY' if False

array([['0', '0', '0', '0'],
       ['0', 'YAY', '0', '0'],
       ['0', '0', '0', '0']], dtype='<U21')

In [130]:
import pandas as pd

In [131]:
pd.set_option("display.max_columns", None)

In [132]:
trees = pd.DataFrame({
    'name': ['sugar maple', 'black oak', 'white ash', 'douglas fir'],
    'avg_lifespan': [300, 100, 260, 450]
})

trees

name  avg_lifespan
0  sugar maple           300
1    black oak           100
2    white ash           260
3  douglas fir           450

In [134]:
trees_types = pd.Series(['deciduous', 'deciduous', 'evergreen', 'evergreen'], 
                        name='foliage')
trees_types

0    deciduous
1    deciduous
2    evergreen
3    evergreen
Name: foliage, dtype: object

In [139]:
import os

os.getcwd()

'/Users/kaylielau/Desktop/python-1/06-live-coding'

In [140]:
thefts = pd.read_csv('../data/bicycle-thefts - 4326.csv')

In [141]:
thefts.shape

(25569, 33)

In [142]:
# object dtype represents columns that contain text or mixed types of data
# catch-all for columns that don't fit into more specific types like
# integers, floats, datetime

thefts.dtypes

_id                        int64
OBJECTID                   int64
event_unique_id           object
Primary_Offence           object
Occurrence_Date           object
Occurrence_Year            int64
Occurrence_Month          object
Occurrence_DayOfWeek      object
Occurrence_DayOfMonth      int64
Occurrence_DayOfYear       int64
Occurrence_Hour            int64
Report_Date               object
Report_Year                int64
Report_Month              object
Report_DayOfWeek          object
Report_DayOfMonth          int64
Report_DayOfYear           int64
Report_Hour                int64
Division                  object
City                      object
Hood_ID                   object
NeighbourhoodName         object
Location_Type             object
Premises_Type             object
Bike_Make                 object
Bike_Model                object
Bike_Type                 object
Bike_Speed                 int64
Bike_Colour               object
Cost_of_Bike             float64
Status    

In [143]:
thefts.head()

_id  OBJECTID event_unique_id        Primary_Offence      Occurrence_Date  \
0    1     17744  GO-20179016397            THEFT UNDER  2017-10-03T00:00:00   
1    2     17759  GO-20172033056  THEFT UNDER - BICYCLE  2017-11-08T00:00:00   
2    3     17906  GO-20189030822  THEFT UNDER - BICYCLE  2018-09-14T00:00:00   
3    4     17962   GO-2015804467            THEFT UNDER  2015-05-07T00:00:00   
4    5     17963  GO-20159002781            THEFT UNDER  2015-05-16T00:00:00   

   Occurrence_Year Occurrence_Month Occurrence_DayOfWeek  \
0             2017          October              Tuesday   
1             2017         November            Wednesday   
2             2018        September               Friday   
3             2015              May             Thursday   
4             2015              May             Saturday   

   Occurrence_DayOfMonth  Occurrence_DayOfYear  Occurrence_Hour  \
0                      3                   276               14   
1                      8                   312                3   
2                     14                   257                9   
3                      7                   127               18   
4                     16                   136               12   

           Report_Date  Report_Year Report_Month Report_DayOfWeek  \
0  2017-10-03T00:00:00         2017      October          Tuesday   
1  2017-11-08T00:00:00         2017     November        Wednesday   
2  2018-09-17T00:00:00         2018    September           Monday   
3  2015-05-14T00:00:00         2015          May         Thursday   
4  2015-05-16T00:00:00         2015          May         Saturday   

   Report_DayOfMonth  Report_DayOfYear  Report_Hour Division     City Hood_ID  \
0                  3               276           18      D22  Toronto      15   
1                  8               312           22      D22  Toronto      15   
2                 17               260           16      D22  Toronto      15   
3                 14               134           14      D22  Toronto      15   
4                 16               136           15      D22  Toronto      15   

     NeighbourhoodName                                      Location_Type  \
0  Kingsway South (15)  Streets, Roads, Highways (Bicycle Path, Privat...   
1  Kingsway South (15)  Single Home, House (Attach Garage, Cottage, Mo...   
2  Kingsway South (15)                                 Ttc Subway Station   
3  Kingsway South (15)                                 Ttc Subway Station   
4  Kingsway South (15)                                 Ttc Subway Station   

  Premises_Type     Bike_Make  Bike_Model Bike_Type  Bike_Speed Bike_Colour  \
0       Outside            GI    ESCAPE 2        OT           7         BLK   
1         House  UNKNOWN MAKE         NaN        TO           1         BLK   
2       Transit            OT  CROSSTRAIL        MT          24         BLK   
3       Transit            GT         NaN        TO          10      BLKDGR   
4       Transit            GI         NaN        MT           6         RED   

   Cost_of_Bike     Status  ObjectId2  \
0         700.0     STOLEN          1   
1        1100.0  RECOVERED          2   
2         904.0     STOLEN          3   
3         400.0     STOLEN          4   
4         600.0     STOLEN          5   

                                            geometry  
0  {'type': 'Point', 'coordinates': (-79.50655965...  
1  {'type': 'Point', 'coordinates': (-79.50484874...  
2  {'type': 'Point', 'coordinates': (-79.51170915...  
3  {'type': 'Point', 'coordinates': (-79.51170915...  
4  {'type': 'Point', 'coordinates': (-79.51132657...

In [144]:
thefts.tail()

_id  OBJECTID event_unique_id        Primary_Offence  \
25564  25565      9361   GO-2015543181         MISCHIEF UNDER   
25565  25566     11318  GO-20169004589            THEFT UNDER   
25566  25567     11462  GO-20169005434            THEFT UNDER   
25567  25568     11695  GO-20161170896            THEFT UNDER   
25568  25569     11883  GO-20169007653  THEFT UNDER - BICYCLE   

           Occurrence_Date  Occurrence_Year Occurrence_Month  \
25564  2015-04-01T00:00:00             2015            April   
25565  2016-05-16T00:00:00             2016              May   
25566  2016-06-04T00:00:00             2016             June   
25567  2016-07-04T00:00:00             2016             July   
25568  2016-07-22T00:00:00             2016             July   

      Occurrence_DayOfWeek  Occurrence_DayOfMonth  Occurrence_DayOfYear  \
25564            Wednesday                      1                    91   
25565               Monday                     16                   137   
25566             Saturday                      4                   156   
25567               Monday                      4                   186   
25568               Friday                     22                   204   

       Occurrence_Hour          Report_Date  Report_Year Report_Month  \
25564               17  2015-04-01T00:00:00         2015        April   
25565               21  2016-05-16T00:00:00         2016          May   
25566               22  2016-06-07T00:00:00         2016         June   
25567               20  2016-07-04T00:00:00         2016         July   
25568                9  2016-07-23T00:00:00         2016         July   

      Report_DayOfWeek  Report_DayOfMonth  Report_DayOfYear  Report_Hour  \
25564        Wednesday                  1                91           19   
25565           Monday                 16               137           21   
25566          Tuesday                  7               159           16   
25567           Monday                  4               186           20   
25568         Saturday                 23               205           11   

      Division     City Hood_ID NeighbourhoodName  \
25564      D42  Toronto     132     Malvern (132)   
25565      D42  Toronto     132     Malvern (132)   
25566      D42  Toronto     132     Malvern (132)   
25567      D42  Toronto     132     Malvern (132)   
25568      D42  Toronto     132     Malvern (132)   

                                           Location_Type Premises_Type  \
25564  Parking Lots (Apt., Commercial Or Non-Commercial)       Outside   
25565  Single Home, House (Attach Garage, Cottage, Mo...         House   
25566                   Apartment (Rooming House, Condo)     Apartment   
25567  Other Commercial / Corporate Places (For Profi...    Commercial   
25568  Parking Lots (Apt., Commercial Or Non-Commercial)       Outside   

          Bike_Make       Bike_Model Bike_Type  Bike_Speed Bike_Colour  \
25564  UNKNOWN MAKE     BMX WILD MAN        RG           0         SIL   
25565            SC              NaN        OT          14         NaN   
25566            SC           ANTRIM        MT          24         WHI   
25567  UNKNOWN MAKE              NaN        SC           1         NaN   
25568            SU  ASCENT MOUNTAIN        MT          21         ONG   

       Cost_of_Bike  Status  ObjectId2  \
25564         600.0  STOLEN      25565   
25565         900.0  STOLEN      25566   
25566         700.0  STOLEN      25567   
25567        3000.0  STOLEN      25568   
25568         200.0  STOLEN      25569   

                                                geometry  
25564  {'type': 'Point', 'coordinates': (-79.21555349...  
25565  {'type': 'Point', 'coordinates': (-79.21767046...  
25566  {'type': 'Point', 'coordinates': (-79.2360175,...  
25567  {'type': 'Point', 'coordinates': (-79.20060719...  
25568  {'type': 'Point', 'coordinates': (-79.23734742...

In [145]:
thefts.head(10)

_id  OBJECTID event_unique_id        Primary_Offence      Occurrence_Date  \
0    1     17744  GO-20179016397            THEFT UNDER  2017-10-03T00:00:00   
1    2     17759  GO-20172033056  THEFT UNDER - BICYCLE  2017-11-08T00:00:00   
2    3     17906  GO-20189030822  THEFT UNDER - BICYCLE  2018-09-14T00:00:00   
3    4     17962   GO-2015804467            THEFT UNDER  2015-05-07T00:00:00   
4    5     17963  GO-20159002781            THEFT UNDER  2015-05-16T00:00:00   
5    6     18003  GO-20151861057            THEFT UNDER  2015-09-01T00:00:00   
6    7     18013  GO-20169001537            THEFT UNDER  2016-02-18T00:00:00   
7    8     20993   GO-2019819460            THEFT UNDER  2019-05-01T00:00:00   
8    9     21209  GO-20179014159            THEFT UNDER  2017-09-06T00:00:00   
9   10     21999  GO-20149003203            THEFT UNDER  2014-05-07T00:00:00   

   Occurrence_Year Occurrence_Month Occurrence_DayOfWeek  \
0             2017          October              Tuesday   
1             2017         November            Wednesday   
2             2018        September               Friday   
3             2015              May             Thursday   
4             2015              May             Saturday   
5             2015        September              Tuesday   
6             2016         February             Thursday   
7             2019              May            Wednesday   
8             2017        September            Wednesday   
9             2014              May            Wednesday   

   Occurrence_DayOfMonth  Occurrence_DayOfYear  Occurrence_Hour  \
0                      3                   276               14   
1                      8                   312                3   
2                     14                   257                9   
3                      7                   127               18   
4                     16                   136               12   
5                      1                   244                0   
6                     18                    49                9   
7                      1                   121               13   
8                      6                   249                8   
9                      7                   127               18   

           Report_Date  Report_Year Report_Month Report_DayOfWeek  \
0  2017-10-03T00:00:00         2017      October          Tuesday   
1  2017-11-08T00:00:00         2017     November        Wednesday   
2  2018-09-17T00:00:00         2018    September           Monday   
3  2015-05-14T00:00:00         2015          May         Thursday   
4  2015-05-16T00:00:00         2015          May         Saturday   
5  2015-10-29T00:00:00         2015      October         Thursday   
6  2016-02-18T00:00:00         2016     February         Thursday   
7  2019-05-06T00:00:00         2019          May           Monday   
8  2017-09-06T00:00:00         2017    September        Wednesday   
9  2014-05-07T00:00:00         2014          May        Wednesday   

   Report_DayOfMonth  Report_DayOfYear  Report_Hour Division     City Hood_ID  \
0                  3               276           18      D22  Toronto      15   
1                  8               312           22      D22  Toronto      15   
2                 17               260           16      D22  Toronto      15   
3                 14               134           14      D22  Toronto      15   
4                 16               136           15      D22  Toronto      15   
5                 29               302           18      D22  Toronto      15   
6                 18                49           23      D22  Toronto      15   
7                  6               126           11      D22  Toronto      15   
8                  6               249           21      D22  Toronto      15   
9                  7               127           19      D22  Toronto      15   

     NeighbourhoodName                                      Location_Ty

In [146]:
thefts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25569 entries, 0 to 25568
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   _id                    25569 non-null  int64  
 1   OBJECTID               25569 non-null  int64  
 2   event_unique_id        25569 non-null  object 
 3   Primary_Offence        25569 non-null  object 
 4   Occurrence_Date        25569 non-null  object 
 5   Occurrence_Year        25569 non-null  int64  
 6   Occurrence_Month       25569 non-null  object 
 7   Occurrence_DayOfWeek   25569 non-null  object 
 8   Occurrence_DayOfMonth  25569 non-null  int64  
 9   Occurrence_DayOfYear   25569 non-null  int64  
 10  Occurrence_Hour        25569 non-null  int64  
 11  Report_Date            25569 non-null  object 
 12  Report_Year            25569 non-null  int64  
 13  Report_Month           25569 non-null  object 
 14  Report_DayOfWeek       25569 non-null  object 
 15  Re